In [1]:
import numpy as np

Initially I think about decompose matrix by spectral(eigendecomposition) to the matrix of eigenvectors and diagonal matrix of eigenvalues. But unfortunately, this matrix is not diagonalizable. So I try to use fact that it is triangular. let $D = diag(A)$

$B = (A - D)$

and $B$ is nilpotent, for any $n$-dimensional nilpotent matrix $B^k=0$, $\forall k : k \geq r $ and $r \leq n$

And for this case $k=3$:

In [19]:
A = np.array([[1., 0., 0.], [1., 1., 0.], [0., -1., 1000.]], dtype=np.float64)
B = A - np.diag(A.diagonal())
print('Power 2')
print(B@B)
print('Power 3')
print(B@B@B)

Power 2
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [-1.  0.  0.]]
Power 3
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


And the idea is that I can raise $D$ to the power $n$ efficiently since it is diagonal, and I can get power element-wise:
$A^n=(D + B)^n=D^n + C_1^nD^nB +C_2^nD^{n-1}B^2 + 0 \dots$


But then I realize that for this formula it is necessary to DB=BD, which is false for this case:(

This leads to the fact that the nilpotent property completely loses its helpful in terms of the efficiency of calculations, for example, for degree 4:

$(D+B)^4 = D^4 + D^3B + D^2BD +D^2B^2 + DBD^2 + DBDB + DB^2D + DB^3 + BD^3 + BD^2B + BDBD + BDB^2 + B^2D^2 + B^2DB + B^3D + B^4 $

And in this sum it is possible to nullify only 3 elements out of 16.

I could no come up with a way to effectively raise this matrix to a power, so I just used Numpy:

In [67]:
def matrix_to_power(n):
    if n < 103:
        return np.linalg.matrix_power(A, n)
    else:
        print('Too big power')
        return None

In [70]:
print(matrix_to_power(50))

[[ 1.000000e+000  0.000000e+000  0.000000e+000]
 [ 5.000000e+001  1.000000e+000  0.000000e+000]
 [-1.002003e+144 -1.001001e+147  1.000000e+150]]


In [69]:
print(matrix_to_power(103))

Too big power
None
